version: '3.8'  
services:  
  postgres:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:
      DATABASE_HOST: 127.0.0.0
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:  
      - "5432:5432"  
  pgadmin:  
    container_name: pgadmin4_container  
    image: dpage/pgadmin4  
    restart: always  
    environment:  
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:  
      - "80:80"
    depends_on:
      - postgres